const LANGS=[
 ['ru','🇷🇺','Русский','Россия'],['en','🇬🇧','English','United Kingdom'],['es','🇪🇸','Español','España'],['de','🇩🇪','Deutsch','Deutschland'],['fr','🇫🇷','Français','France'],['it','🇮🇹','Italiano','Italia'],['pt','🇵🇹','Português','Portugal'],['tr','🇹🇷','Türkçe','Türkiye'],['ar','🇸🇦','العربية','العربية'],['zh','🇨🇳','中文','中国'],['ja','🇯🇵','日本語','日本'],['ko','🇰🇷','한국어','대한민국'],['hy','🇦🇲','Հայերեն','Հայաստան']
];

const en={
 nav_features:'Features',nav_products:'Products',nav_security:'Security',nav_family:'Family Constellation',nav_support:'Support',download:'Download',
 hero_eyebrow:'MORE THAN JUST AN APP',hero_title:'Your personal AI assistant in the real world',hero_lead:'Work. Study. Documents. Ideas. Security. Communication. Everything in one ecosystem.',hero_cta:'Choose platform',hero_more:'Explore features',
 fact_one:'One ecosystem',fact_one_sub:'instead of dozens of services',fact_private:'Privacy',fact_private_sub:'under your control',fact_devices:'Across devices',fact_devices_sub:'one familiar logic',
 float_label:'LEKSA ECOSYSTEM',float_title:'AI, communication and documents — in one place',float_ai:'AI Assistant',float_ai_sub:'Ideas, translation, everyday help',
 rail_one:'ALL IN ONE',rail_one_sub:'Less app switching',rail_two:'UNDER CONTROL',rail_two_sub:'Privacy by default',rail_three:'ANY LANGUAGE',rail_three_sub:'Interface and communication',rail_four:'NO LIMITS',rail_four_sub:'For everyday tasks',
 features_eyebrow:'FEATURES',features_title:'One tool. Less digital chaos.',features_lead:'LEKSA brings together the tools you actually use every day.',
 f_ai_t:'AI Chat',f_ai_d:'Answers, plans, ideas, translation, explanations and everyday assistance.',f_docs_t:'My documents',f_docs_d:'Scanning, OCR, PDF, Word and Excel. Edit, export and share.',f_notes_t:'Notebook',f_notes_d:'Voice and text notes, thoughts, ideas and tasks — without the noise.',f_msg_t:'Messenger',f_msg_d:'Chats, files, location, voice, video, groups and conferences.',f_vault_t:'Vault',f_vault_d:'Passwords, secret notes and important documents in a protected space.',f_person_t:'Personalization',f_person_d:'Themes, language, voice, profile and privacy settings — made yours.',
 products_eyebrow:'OUR PRODUCTS',products_title:'Technology for your freedom',product_ai_desc:'AI assistant, Messenger, Office, Notebook, Vault and personalization in one application.',product_key_desc:'A hardware key designed to add physical control over sensitive access and protected operations.',learn_more:'Learn more',about_product:'About product',
 docs_eyebrow:'DOCUMENT WORKSPACE',docs_title:'Documents should not become another headache.',docs_desc:'Scan, recognize, edit and export. Keep the working file in Documents while the original can stay safely separated.',msg_eyebrow:'MESSENGER',msg_title:'From a message to a conference.',msg_desc:'Private and group chats, photos and files, voice and video calls, group settings and conferences.',
 security_eyebrow:'SECURITY',security_title:'Your data. Your rules.',security_lead:'Privacy does not need a show. It simply needs to work.',s_local_t:'Local storage',s_local_d:'Sensitive data stays under the device owner’s control.',s_identity_t:'LEKSA ID',s_identity_d:'Connections are built around a unique identifier, not a public people directory.',s_control_t:'Privacy controls',s_control_d:'You decide what to show and who can reach you.',s_secure_t:'Protected workflows',s_secure_d:'Vault, private documents and the future SecureKey add another layer of control.',
 family_title:'Close people. Strong bonds. One digital space.',family_desc:'LEKSA’s family direction for shared routines, organization, communication and a safer space for people you care about.',family_cta:'View concept',
 support_eyebrow:'SUPPORT',support_title:'Human support without a maze.',support_desc:'Tell us about a problem, suggestion or idea. We will prepare a message for LEKSA support.',form_name:'Name',form_email:'Email',form_message:'Message',form_send:'Contact support',form_note:'Your mail app will open with a prepared message.',
 cta_eyebrow:'LEKSA AI',cta_title:'Ready to try the ecosystem?',cta_desc:'Choose your platform.',privacy:'Privacy policy',terms:'Terms of use'
};
const ru={
 nav_features:'Возможности',nav_products:'Продукты',nav_security:'Безопасность',nav_family:'Family Constellation',nav_support:'Поддержка',download:'Скачать',
 hero_eyebrow:'БОЛЬШЕ, ЧЕМ ПРОСТО ПРИЛОЖЕНИЕ',hero_title:'Твой личный AI‑помощник в реальном мире',hero_lead:'Работа. Учёба. Документы. Идеи. Безопасность. Общение. Всё — в одной экосистеме.',hero_cta:'Выбрать платформу',hero_more:'Посмотреть возможности',
 fact_one:'Одна экосистема',fact_one_sub:'вместо десятка сервисов',fact_private:'Приватность',fact_private_sub:'под твоим контролем',fact_devices:'На всех устройствах',fact_devices_sub:'единая логика',
 float_label:'ЭКОСИСТЕМА LEKSA',float_title:'AI, связь и документы — в одном месте',float_ai:'AI‑помощник',float_ai_sub:'Идеи, перевод, помощь',
 rail_one:'ВСЁ В ОДНОМ',rail_one_sub:'Меньше переключений',rail_two:'ПОД КОНТРОЛЕМ',rail_two_sub:'Приватность по умолчанию',rail_three:'ЛЮБОЙ ЯЗЫК',rail_three_sub:'Интерфейс и общение',rail_four:'БЕЗ ГРАНИЦ',rail_four_sub:'Для повседневных задач',
 features_eyebrow:'ВОЗМОЖНОСТИ',features_title:'Один инструмент. Без лишнего хаоса.',features_lead:'LEKSA объединяет функции, которыми ты действительно пользуешься каждый день.',
 f_ai_t:'Чат с ИИ',f_ai_d:'Ответы, планы, идеи, перевод, объяснения и помощь в повседневных задачах.',f_docs_t:'Мои документы',f_docs_d:'Сканирование, OCR, PDF, Word и Excel. Редактирование, экспорт и отправка.',f_notes_t:'Блокнот',f_notes_d:'Голосовые и текстовые заметки, мысли, идеи и задачи — без лишнего шума.',f_msg_t:'Мессенджер',f_msg_d:'Чаты, файлы, геопозиция, голос, видео, группы и конференции.',f_vault_t:'Сейф',f_vault_d:'Пароли, секретные заметки и важные документы в защищённом пространстве.',f_person_t:'Персонализация',f_person_d:'Темы, язык, голос, профиль и настройки приватности — под тебя.',
 products_eyebrow:'НАШИ ПРОДУКТЫ',products_title:'Технологии для твоей свободы',product_ai_desc:'AI‑помощник, Messenger, Office, Notebook, Vault и персонализация в одном приложении.',product_key_desc:'Аппаратный ключ для дополнительного физического контроля доступа к важным данным и защищённым операциям.',learn_more:'Узнать больше',about_product:'О продукте',
 docs_eyebrow:'РАБОТА С ДОКУМЕНТАМИ',docs_title:'Документы — не отдельная головная боль.',docs_desc:'Сканируй, распознавай, редактируй и экспортируй. Рабочая версия остаётся в документах, а исходник может храниться отдельно и не мешать.',msg_eyebrow:'МЕССЕНДЖЕР',msg_title:'От сообщения до конференции.',msg_desc:'Личные и групповые чаты, фото и файлы, звонки, видеосвязь, группы с настройками и конференции.',
 security_eyebrow:'БЕЗОПАСНОСТЬ',security_title:'Твои данные — твои правила.',security_lead:'Без лишней демонстрации приватности. Она просто должна работать.',s_local_t:'Локальное хранение',s_local_d:'Чувствительные данные остаются под контролем владельца устройства.',s_identity_t:'LEKSA ID',s_identity_d:'Связь строится вокруг уникального идентификатора, а не публичного списка людей.',s_control_t:'Настройки приватности',s_control_d:'Пользователь сам решает, что показывать и кому быть доступным.',s_secure_t:'Защищённые сценарии',s_secure_d:'Сейф, приватные документы и будущий SecureKey усиливают контроль над важными данными.',
 family_title:'Близкие люди. Сильные связи. Одно цифровое пространство.',family_desc:'Семейное направление LEKSA для совместных сценариев, организации, связи и безопасного пространства для близких.',family_cta:'Посмотреть концепцию',
 support_eyebrow:'ПОДДЕРЖКА',support_title:'Нормальная поддержка без квестов.',support_desc:'Опиши проблему, предложение или идею. Мы подготовим письмо в поддержку LEKSA.',form_name:'Имя',form_email:'Email',form_message:'Сообщение',form_send:'Написать в поддержку',form_note:'Откроется установленное почтовое приложение с готовым письмом.',
 cta_eyebrow:'LEKSA AI',cta_title:'Готов попробовать экосистему в действии?',cta_desc:'Выбери свою платформу.',privacy:'Политика конфиденциальности',terms:'Условия использования'
};

const localePatch={
 es:{nav_features:'Funciones',nav_products:'Productos',nav_security:'Seguridad',nav_support:'Soporte',download:'Descargar',hero_eyebrow:'MÁS QUE UNA APLICACIÓN',hero_title:'Tu asistente personal de IA en el mundo real',hero_lead:'Trabajo. Estudio. Documentos. Ideas. Seguridad. Comunicación. Todo en un ecosistema.',hero_cta:'Elegir plataforma',hero_more:'Explorar funciones',features_eyebrow:'FUNCIONES',features_title:'Una herramienta. Menos caos digital.',features_lead:'LEKSA reúne las herramientas que realmente usas cada día.',f_ai_t:'Chat con IA',f_ai_d:'Respuestas, planes, ideas, traducción, explicaciones y ayuda diaria.',f_docs_t:'Mis documentos',f_docs_d:'Escaneo, OCR, PDF, Word y Excel. Edita, exporta y comparte.',f_notes_t:'Notas',f_notes_d:'Notas de voz y texto, ideas y tareas sin ruido innecesario.',f_msg_t:'Mensajero',f_msg_d:'Chats, archivos, ubicación, voz, vídeo, grupos y conferencias.',f_vault_t:'Bóveda',f_vault_d:'Contraseñas, notas secretas y documentos importantes en un espacio protegido.',f_person_t:'Personalización',f_person_d:'Temas, idioma, voz, perfil y privacidad a tu manera.',products_eyebrow:'NUESTROS PRODUCTOS',products_title:'Tecnología para tu libertad',docs_title:'Los documentos no deberían ser otro problema.',msg_title:'De un mensaje a una conferencia.',security_title:'Tus datos. Tus reglas.',family_title:'Personas cercanas. Vínculos fuertes. Un espacio digital.',support_title:'Soporte humano sin laberintos.',form_name:'Nombre',form_message:'Mensaje',form_send:'Contactar con soporte',cta_title:'¿Listo para probar el ecosistema?',privacy:'Política de privacidad',terms:'Términos de uso'},
 de:{nav_features:'Funktionen',nav_products:'Produkte',nav_security:'Sicherheit',nav_support:'Support',download:'Download',hero_eyebrow:'MEHR ALS NUR EINE APP',hero_title:'Dein persönlicher KI‑Assistent in der realen Welt',hero_lead:'Arbeit. Studium. Dokumente. Ideen. Sicherheit. Kommunikation. Alles in einem Ökosystem.',hero_cta:'Plattform wählen',hero_more:'Funktionen entdecken',features_eyebrow:'FUNKTIONEN',features_title:'Ein Werkzeug. Weniger digitales Chaos.',f_ai_t:'KI‑Chat',f_docs_t:'Meine Dokumente',f_notes_t:'Notizen',f_msg_t:'Messenger',f_vault_t:'Tresor',f_person_t:'Personalisierung',products_eyebrow:'UNSERE PRODUKTE',products_title:'Technologie für deine Freiheit',docs_title:'Dokumente sollten kein zusätzliches Problem sein.',msg_title:'Von der Nachricht zur Konferenz.',security_title:'Deine Daten. Deine Regeln.',family_title:'Nahe Menschen. Starke Verbindungen. Ein digitaler Raum.',support_title:'Menschlicher Support ohne Umwege.',form_name:'Name',form_message:'Nachricht',form_send:'Support kontaktieren',cta_title:'Bereit, das Ökosystem zu testen?',privacy:'Datenschutz',terms:'Nutzungsbedingungen'},
 fr:{nav_features:'Fonctionnalités',nav_products:'Produits',nav_security:'Sécurité',nav_support:'Support',download:'Télécharger',hero_eyebrow:'BIEN PLUS QU’UNE APPLICATION',hero_title:'Votre assistant IA personnel dans le monde réel',hero_lead:'Travail. Études. Documents. Idées. Sécurité. Communication. Tout dans un seul écosystème.',hero_cta:'Choisir la plateforme',hero_more:'Découvrir les fonctions',features_eyebrow:'FONCTIONNALITÉS',features_title:'Un outil. Moins de chaos numérique.',f_ai_t:'Chat IA',f_docs_t:'Mes documents',f_notes_t:'Notes',f_msg_t:'Messagerie',f_vault_t:'Coffre',f_person_t:'Personnalisation',products_eyebrow:'NOS PRODUITS',products_title:'La technologie au service de votre liberté',docs_title:'Les documents ne devraient pas être un problème de plus.',msg_title:'Du message à la conférence.',security_title:'Vos données. Vos règles.',family_title:'Des proches. Des liens forts. Un espace numérique.',support_title:'Un support humain, sans labyrinthe.',form_name:'Nom',form_message:'Message',form_send:'Contacter le support',cta_title:'Prêt à essayer l’écosystème ?',privacy:'Politique de confidentialité',terms:'Conditions d’utilisation'},
 it:{nav_features:'Funzioni',nav_products:'Prodotti',nav_security:'Sicurezza',nav_support:'Supporto',download:'Scarica',hero_eyebrow:'PIÙ DI UNA SEMPLICE APP',hero_title:'Il tuo assistente AI personale nel mondo reale',hero_lead:'Lavoro. Studio. Documenti. Idee. Sicurezza. Comunicazione. Tutto in un unico ecosistema.',hero_cta:'Scegli piattaforma',hero_more:'Scopri le funzioni',features_eyebrow:'FUNZIONI',features_title:'Uno strumento. Meno caos digitale.',f_ai_t:'Chat AI',f_docs_t:'I miei documenti',f_notes_t:'Note',f_msg_t:'Messenger',f_vault_t:'Cassaforte',f_person_t:'Personalizzazione',products_eyebrow:'I NOSTRI PRODOTTI',products_title:'Tecnologia per la tua libertà',docs_title:'I documenti non dovrebbero diventare un altro problema.',msg_title:'Da un messaggio a una conferenza.',security_title:'I tuoi dati. Le tue regole.',family_title:'Persone vicine. Legami forti. Uno spazio digitale.',support_title:'Supporto umano senza labirinti.',form_name:'Nome',form_message:'Messaggio',form_send:'Contatta il supporto',cta_title:'Pronto a provare l’ecosistema?',privacy:'Privacy',terms:'Termini di utilizzo'},
 pt:{nav_features:'Recursos',nav_products:'Produtos',nav_security:'Segurança',nav_support:'Suporte',download:'Baixar',hero_eyebrow:'MAIS DO QUE UM APLICATIVO',hero_title:'Seu assistente pessoal de IA no mundo real',hero_lead:'Trabalho. Estudo. Documentos. Ideias. Segurança. Comunicação. Tudo em um ecossistema.',hero_cta:'Escolher plataforma',hero_more:'Explorar recursos',features_eyebrow:'RECURSOS',features_title:'Uma ferramenta. Menos caos digital.',f_ai_t:'Chat com IA',f_docs_t:'Meus documentos',f_notes_t:'Notas',f_msg_t:'Mensageiro',f_vault_t:'Cofre',f_person_t:'Personalização',products_eyebrow:'NOSSOS PRODUTOS',products_title:'Tecnologia para sua liberdade',docs_title:'Documentos não deveriam virar outro problema.',msg_title:'De uma mensagem a uma conferência.',security_title:'Seus dados. Suas regras.',family_title:'Pessoas próximas. Laços fortes. Um espaço digital.',support_title:'Suporte humano sem labirintos.',form_name:'Nome',form_message:'Mensagem',form_send:'Falar com o suporte',cta_title:'Pronto para testar o ecossistema?',privacy:'Política de privacidade',terms:'Termos de uso'},
 tr:{nav_features:'Özellikler',nav_products:'Ürünler',nav_security:'Güvenlik',nav_support:'Destek',download:'İndir',hero_eyebrow:'BİR UYGULAMADAN DAHA FAZLASI',hero_title:'Gerçek dünyadaki kişisel yapay zekâ asistanın',hero_lead:'İş. Eğitim. Belgeler. Fikirler. Güvenlik. İletişim. Hepsi tek ekosistemde.',hero_cta:'Platform seç',hero_more:'Özellikleri keşfet',features_eyebrow:'ÖZELLİKLER',features_title:'Tek araç. Daha az dijital karmaşa.',f_ai_t:'Yapay zekâ sohbeti',f_docs_t:'Belgelerim',f_notes_t:'Notlar',f_msg_t:'Mesajlaşma',f_vault_t:'Kasa',f_person_t:'Kişiselleştirme',products_eyebrow:'ÜRÜNLERİMİZ',products_title:'Özgürlüğün için teknoloji',docs_title:'Belgeler başka bir sorun olmamalı.',msg_title:'Mesajdan konferansa.',security_title:'Verilerin. Kuralların.',family_title:'Yakın insanlar. Güçlü bağlar. Tek dijital alan.',support_title:'Karmaşasız, insani destek.',form_name:'Ad',form_message:'Mesaj',form_send:'Desteğe ulaş',cta_title:'Ekosistemi denemeye hazır mısın?',privacy:'Gizlilik politikası',terms:'Kullanım koşulları'},
 ar:{nav_features:'الميزات',nav_products:'المنتجات',nav_security:'الأمان',nav_support:'الدعم',download:'تنزيل',hero_eyebrow:'أكثر من مجرد تطبيق',hero_title:'مساعدك الشخصي بالذكاء الاصطناعي في العالم الحقيقي',hero_lead:'العمل. الدراسة. المستندات. الأفكار. الأمان. التواصل. كل شيء في منظومة واحدة.',hero_cta:'اختر المنصة',hero_more:'استكشف الميزات',features_eyebrow:'الميزات',features_title:'أداة واحدة. فوضى رقمية أقل.',f_ai_t:'محادثة AI',f_docs_t:'مستنداتي',f_notes_t:'الملاحظات',f_msg_t:'المراسلة',f_vault_t:'الخزنة',f_person_t:'التخصيص',products_eyebrow:'منتجاتنا',products_title:'تقنية لحريتك',docs_title:'لا ينبغي أن تصبح المستندات مشكلة إضافية.',msg_title:'من رسالة إلى مؤتمر.',security_title:'بياناتك. قواعدك.',family_title:'أشخاص قريبون. روابط قوية. مساحة رقمية واحدة.',support_title:'دعم إنساني بلا متاهات.',form_name:'الاسم',form_message:'الرسالة',form_send:'تواصل مع الدعم',cta_title:'هل أنت مستعد لتجربة المنظومة؟',privacy:'سياسة الخصوصية',terms:'شروط الاستخدام'},
 zh:{nav_features:'功能',nav_products:'产品',nav_security:'安全',nav_support:'支持',download:'下载',hero_eyebrow:'不只是一个应用',hero_title:'现实世界中的个人 AI 助手',hero_lead:'工作。学习。文档。想法。安全。沟通。全部集中在一个生态系统中。',hero_cta:'选择平台',hero_more:'探索功能',features_eyebrow:'功能',features_title:'一个工具，更少数字混乱。',f_ai_t:'AI 聊天',f_docs_t:'我的文档',f_notes_t:'笔记',f_msg_t:'通讯',f_vault_t:'保险库',f_person_t:'个性化',products_eyebrow:'我们的产品',products_title:'为你的自由而生的技术',docs_title:'文档不该成为新的麻烦。',msg_title:'从消息到会议。',security_title:'你的数据，你的规则。',family_title:'亲近的人。牢固的联系。一个数字空间。',support_title:'没有迷宫的人性化支持。',form_name:'姓名',form_message:'消息',form_send:'联系支持',cta_title:'准备好体验这个生态系统了吗？',privacy:'隐私政策',terms:'使用条款'},
 ja:{nav_features:'機能',nav_products:'製品',nav_security:'セキュリティ',nav_support:'サポート',download:'ダウンロード',hero_eyebrow:'ただのアプリではない',hero_title:'現実世界のパーソナルAIアシスタント',hero_lead:'仕事。学習。ドキュメント。アイデア。安全。コミュニケーション。すべてを一つのエコシステムに。',hero_cta:'プラットフォームを選択',hero_more:'機能を見る',features_eyebrow:'機能',features_title:'一つのツール。デジタルの混乱を減らす。',f_ai_t:'AIチャット',f_docs_t:'マイドキュメント',f_notes_t:'ノート',f_msg_t:'メッセンジャー',f_vault_t:'保管庫',f_person_t:'パーソナライズ',products_eyebrow:'製品',products_title:'自由のためのテクノロジー',docs_title:'ドキュメントを新たな悩みにしない。',msg_title:'メッセージから会議まで。',security_title:'あなたのデータ。あなたのルール。',family_title:'大切な人。強いつながり。一つのデジタル空間。',support_title:'迷わない、人のためのサポート。',form_name:'名前',form_message:'メッセージ',form_send:'サポートへ連絡',cta_title:'エコシステムを試してみませんか？',privacy:'プライバシーポリシー',terms:'利用規約'},
 ko:{nav_features:'기능',nav_products:'제품',nav_security:'보안',nav_support:'지원',download:'다운로드',hero_eyebrow:'단순한 앱 그 이상',hero_title:'현실 세계의 개인 AI 어시스턴트',hero_lead:'업무. 학습. 문서. 아이디어. 보안. 커뮤니케이션. 하나의 생태계에 모두.',hero_cta:'플랫폼 선택',hero_more:'기능 살펴보기',features_eyebrow:'기능',features_title:'하나의 도구. 더 적은 디지털 혼란.',f_ai_t:'AI 채팅',f_docs_t:'내 문서',f_notes_t:'노트',f_msg_t:'메신저',f_vault_t:'금고',f_person_t:'개인화',products_eyebrow:'제품',products_title:'당신의 자유를 위한 기술',docs_title:'문서는 또 하나의 골칫거리가 되어선 안 됩니다.',msg_title:'메시지에서 회의까지.',security_title:'당신의 데이터. 당신의 규칙.',family_title:'가까운 사람들. 강한 연결. 하나의 디지털 공간.',support_title:'복잡하지 않은 사람 중심 지원.',form_name:'이름',form_message:'메시지',form_send:'지원 문의',cta_title:'생태계를 사용해 볼 준비가 되셨나요?',privacy:'개인정보처리방침',terms:'이용 약관'},
 hy:{nav_features:'Հնարավորություններ',nav_products:'Արտադրանք',nav_security:'Անվտանգություն',nav_support:'Աջակցություն',download:'Ներբեռնել',hero_eyebrow:'ԱՎԵԼԻՆ, ՔԱՆ ՊԱՐԶԱՊԵՍ ՀԱՎԵԼՎԱԾ',hero_title:'Քո անձնական AI օգնականը իրական աշխարհում',hero_lead:'Աշխատանք։ Ուսում։ Փաստաթղթեր։ Գաղափարներ։ Անվտանգություն։ Հաղորդակցություն։ Ամեն ինչ՝ մեկ էկոհամակարգում։',hero_cta:'Ընտրել հարթակը',hero_more:'Դիտել հնարավորությունները',features_eyebrow:'ՀՆԱՐԱՎՈՐՈՒԹՅՈՒՆՆԵՐ',features_title:'Մեկ գործիք։ Ավելի քիչ թվային խառնաշփոթ։',f_ai_t:'AI զրույց',f_docs_t:'Իմ փաստաթղթերը',f_notes_t:'Նոթատետր',f_msg_t:'Մեսենջեր',f_vault_t:'Պահոց',f_person_t:'Անհատականացում',products_eyebrow:'ՄԵՐ ԱՐՏԱԴՐԱՆՔԸ',products_title:'Տեխնոլոգիա քո ազատության համար',docs_title:'Փաստաթղթերը չպետք է դառնան նոր խնդիր։',msg_title:'Հաղորդագրությունից մինչև կոնֆերանս։',security_title:'Քո տվյալները։ Քո կանոնները։',family_title:'Մոտ մարդիկ։ Ուժեղ կապեր։ Մեկ թվային տարածք։',support_title:'Մարդկային աջակցություն՝ առանց բարդությունների։',form_name:'Անուն',form_message:'Հաղորդագրություն',form_send:'Կապվել աջակցության հետ',cta_title:'Պատրա՞ստ ես փորձել էկոհամակարգը։',privacy:'Գաղտնիության քաղաքականություն',terms:'Օգտագործման պայմաններ'}
};
const translations={ru,en};for(const [k,v] of Object.entries(localePatch)) translations[k]={...en,...v};

const langToggle=document.getElementById('langToggle'),langMenu=document.getElementById('langMenu'),langFlag=document.getElementById('langFlag'),langName=document.getElementById('langName');
const flagSrc=code=>`assets/flags/${code}.svg`;
function buildLangMenu(){langMenu.innerHTML='';LANGS.forEach(([code,flag,name,country])=>{const b=document.createElement('button');b.className='lang-option';b.dataset.lang=code;b.innerHTML=`<img class=\"lang-option__flag\" src=\"${flagSrc(code)}\" alt=\"${name}\" onerror=\"this.style.display='none'\"><span><b>${name}</b><small>${country}</small></span>`;b.addEventListener('click',()=>{setLang(code);toggleLang(false)});langMenu.appendChild(b)})}
function toggleLang(force){const open=force??langMenu.hidden;langMenu.hidden=!open;langToggle.setAttribute('aria-expanded',String(open))}
langToggle.addEventListener('click',e=>{e.stopPropagation();toggleLang()});document.addEventListener('click',e=>{if(!e.target.closest('.language'))toggleLang(false)});
function setLang(code){const dict=translations[code]||en;document.documentElement.lang=code;document.documentElement.dir=code==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;el.textContent=dict[key]??en[key]??el.textContent});const info=LANGS.find(x=>x[0]===code)||LANGS[0];langFlag.src=flagSrc(code);langFlag.alt=info[2];langName.textContent=info[2];localStorage.setItem('leksa-lang',code);document.querySelectorAll('.lang-option').forEach(x=>x.classList.toggle('active',x.dataset.lang===code))}
buildLangMenu();setLang(localStorage.getItem('leksa-lang')||'ru');

const hamb=document.getElementById('hamb'),nav=document.querySelector('.nav');hamb.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));

const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.09});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const stars=document.getElementById('stars');for(let i=0;i<42;i++){const s=document.createElement('i');s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=(Math.random()*5)+'s';s.style.animationDuration=(3+Math.random()*6)+'s';stars.appendChild(s)}
if(matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*-10,y=(e.clientY/innerHeight-.5)*-7;document.documentElement.style.setProperty('--px',x+'px');document.documentElement.style.setProperty('--py',y+'px')},{passive:true})}

const modal=document.getElementById('modal'),modalTitle=document.getElementById('modalTitle'),modalBody=document.getElementById('modalBody'),modalActions=document.getElementById('modalActions'),modalEyebrow=document.getElementById('modalEyebrow');
function openModal(title,body,actions='',eyebrow='LEKSA'){modalTitle.textContent=title;modalBody.innerHTML=body;modalActions.innerHTML=actions;modalEyebrow.textContent=eyebrow;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
modal.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.closeModal=closeModal;

const details={
 ai:{ru:['Чат с ИИ','LEKSA AI задуман как ежедневный помощник: объяснять, структурировать, помогать с идеями, текстом, переводом и рабочими задачами.'],en:['AI Chat','LEKSA AI is designed as an everyday assistant for explanations, structure, ideas, writing, translation and practical tasks.']},
 docs:{ru:['Мои документы','Сканирование и OCR, PDF, Word и Excel, редактирование, сохранение и экспорт. Исходники могут храниться отдельно, не мешая рабочим версиям.'],en:['My documents','Scanning and OCR, PDF, Word and Excel, editing, saving and export. Originals can remain separate from working files.']},
 notes:{ru:['Блокнот','Голосовые и текстовые заметки, длинная диктовка, идеи и задачи с быстрым сохранением и возвратом к ним.'],en:['Notebook','Voice and text notes, long dictation, ideas and tasks with fast saving and easy return.']},
 messenger:{ru:['Мессенджер','Личные и групповые чаты, файлы, фото, голосовые сообщения, аудио- и видеозвонки, группы и конференции.'],en:['Messenger','Private and group chats, files, photos, voice messages, audio and video calls, groups and conferences.']},
 vault:{ru:['Сейф','Защищённое пространство для паролей, важных документов и секретных заметок.'],en:['Vault','A protected space for passwords, important documents and secret notes.']},
 personal:{ru:['Персонализация','Профиль, темы, язык, голос и настройки приватности помогают сделать LEKSA своим пространством.'],en:['Personalization','Profile, themes, language, voice and privacy controls make LEKSA feel like your own space.']},
 productAi:{ru:['LEKSA AI','Единая экосистема для помощи, общения, документов, заметок, приватных данных и персонализации.'],en:['LEKSA AI','One ecosystem for assistance, communication, documents, notes, private data and personalization.']},
 secureKey:{ru:['LEKSA SecureKey','Аппаратное направление LEKSA в разработке. Идея — добавить физический фактор контроля к чувствительным операциям и доступу. Сайт не выдаёт устройство за уже готовый продукт.'],en:['LEKSA SecureKey','A hardware direction in development. The goal is to add a physical factor of control to sensitive operations and access. It is not presented as an already released product.']},
 family:{ru:['Family Constellation','Семейное направление LEKSA: общие сценарии, организация, связь и безопасное цифровое пространство для близких.'],en:['Family Constellation','LEKSA’s family direction for shared routines, organization, communication and a safer digital space for loved ones.']}
};
function activeLang(){return document.documentElement.lang||'ru'}
document.querySelectorAll('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.detail,l=activeLang(),pair=details[key]?.[l]||details[key]?.en||['LEKSA',''];openModal(pair[0],`<p>${pair[1]}</p>`) }));

function platformModal(){
  const l=activeLang(),ru=l==='ru';
  openModal(ru?'Скачать LEKSA':'Download LEKSA',
    `<div class="platform-list platform-list--clean">
      <button class="platform" data-p="android"><b>Android</b></button>
      <button class="platform" data-p="windows"><b>Windows</b></button>
      <button class="platform" data-p="ios"><b>iOS</b></button>
      <button class="platform" data-p="macos"><b>macOS</b></button>
    </div>`);
  setTimeout(()=>document.querySelectorAll('.platform[data-p]').forEach(b=>b.onclick=()=>openPlatform(b.dataset.p)),0)
}
function openPlatform(p){
  const ru=activeLang()==='ru';
  const files={android:'downloads/LEKSA-Android.apk',windows:'downloads/LEKSA-Windows.exe'};
  if(files[p]){
    if(location.protocol==='http:'||location.protocol==='https:'){
      fetch(files[p],{method:'HEAD'}).then(r=>{
        if(r.ok){const a=document.createElement('a');a.href=files[p];a.download='';document.body.appendChild(a);a.click();a.remove()}
        else openModal(p==='android'?'Android':'Windows',`<p>${ru?'Файл пока не загружен.':'The file has not been uploaded yet.'}</p>`)
      }).catch(()=>openModal(p==='android'?'Android':'Windows',`<p>${ru?'Файл пока не загружен.':'The file has not been uploaded yet.'}</p>`));
    }else{
      const a=document.createElement('a');a.href=files[p];a.download='';document.body.appendChild(a);a.click();a.remove()
    }
    return;
  }
  openModal(p==='ios'?'iOS':'macOS',`<p>${ru?'Скоро.':'Coming soon.'}</p>`)
}
document.querySelectorAll('[data-open="downloads"]').forEach(b=>b.addEventListener('click',platformModal));

document.getElementById('supportForm').addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('supportName').value.trim(),m=document.getElementById('supportEmail').value.trim(),t=document.getElementById('supportMessage').value.trim();location.href=`mailto:support@leksa.dev?subject=${encodeURIComponent('LEKSA Support — '+n)}&body=${encodeURIComponent('Name: '+n+'\nEmail: '+m+'\n\n'+t)}`});
